from __future__ import division
from QRdecomp import *
import time
import numpy as np

print("Test on square matrix")
A = np.array([[-3,-3,2],[4,1,3],[-9,-4,1],[1,7,0]])
b = np.array([[8],[16],[11],[14]])

Q,R = qrdec(A)
x   = qrback(Q,R,b)
detA = qrdet(Q,R)
Ain  = qrinverse(Q,R)
print("Matrix A")
print(A)
print("Vector b")
print(b)
print("Q matrix of matrix A")
print(Q)
print("R matrix of matrix A")
print(R)
print("Check that Q * R = A?")
print(np.dot(Q,R))
print("Vector x (solution to A * x = b)")
print(x)
print("Check that A * x = b")
print(np.dot(A,x))
print("Absolute value of determinant of matrix A")
print(detA)
print("Inverse matrix of A")
print(Ain)
print("Check that A * Ainverse is the identity matrix I")
print(np.dot(A,Ain))
print("\n")
print("Test on non quadratic matrix")
A1=np.array([[-4,-4,2],[0,2,4],[-3,-2,3],[0,2,5]])
print("Q matrix of A")
print("Matrix A")
print(A1)
Q1,R1=qrdec(A1)
print("Q matrix of A")
print(Q1)
print("R matrix of A")
print(R1)
print("check that Q*R=A")
print(np.dot(Q1,R1))
